--- 
- hosts: myappservers
  become: yes
  tasks: 
  - name: update apt package
    apt:
     update_cache: yes

  - name: install java
    apt:
     name: "{{myjavapack}}"
     state: present 

  - name: jenkins repository key 
    apt_key:
     url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
     state: present
     
  - name: Add jenkins repository 
    apt_repository: 
     repo: deb https://pkg.jenkins.io/debian binary/
     state: present

  - name: Update apt cache
    apt:
     update_cache: yes

  - name: install jenkins
    apt: 
     name: "{{myjenkinspack}}"
     state: present 
    when: ansible_os_family=="Debian"
     
  - name: Ensure Jenkins service is started and enabled
    service:
     name: jenkins
     state: started
     enabled: yes

    


  

