---
- hosts: 172.31.16.43
  become: yes
  tasks: 
  - name: update packages
    apt: 
     update_cache: yes

  - name: upgarde packages 
    apt:
     upgrade: yes 

  - name: install java 
    apt: 
     name: openjdk-17-jdk 
     state: present 

  - name: install zip 
    package: 
     name: zip 
     state: present 

  - name: install unzip
    package: 
     name: unzip
     state: present 

  - name: install postgresql 
    apt: 
     name: postgresql-15
     state: present 
    
  - name: create directory
    file:
     path: /opt/sonarqube
     state: directory 

  - name: SonarQube of download
    get_url: 
     url: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-7.9.5.zip
     dest: /opt/sonarqube
     force_basic_auth: yes
  
  - name: unarchive sonarqube 
    unarchive: 
     src: /opt/sonarqube/sonarqube-7.9.5.zip
     dest: /opt/sonarqube 
     remote_src: yes
  
  - name: add amf user
    user:
     name: sonar 
     create_home: yes

  - name: execute linux command 
    command: sudo chown -R sonar:sonar /opt/sonarqube

  - name: install dovecot 
    apt: 
     name: 
      - dovecot-core 
      - dovecot-imapd 
     state: present 

  - name: create user 
    user:
     name: sonar
     shell: /bin/bash
     password: $6$CoqCfcob6HzgCVMz$5ZCjzRrydn3jBtJeD2QQ1LZu9y9zCD2psMQAHEaZxrm413Keg9t1AOb3Hyx6/8P3v.Q8/LbosZQA3PMXjeMij0
     state: present 

  - name: create postgresql user 
    postgresql_user:
     user: sonar
     password: sonar  
     role_attr_flags: CREATEDB
     login_password: postgres 
     login_user: postgres
     state: present
    



    