--- 
- hosts: mywebservers
  become: yes
  tasks: 
  - name: update apt package
    apt:
     update_cache: yes

  - name: install java
    apt:
     name: openjdk-17-jdk
     state: present 

  - name: jenkins repository key 
    apt_key:
     url: https://pkg.jenkins.io/debian/jenkins.io-2023.key
     state: present
     
  - name: Add jenkins repository 
    apt_repository: 
     repo: "deb https://pkg.jenkins.io/debian binary/"
     state: present

  - name: install jenkins
    apt: 
     pkg: jenkins
     state: present

  - name: Start Jenkins service
    systemd: 
     name: jenkins
     state: started
     enabled: yes

  - name: Verify Jenkins status
    command: systemctl status jenkins
    


  

