--- 
- hosts: 172.31.30.140
  become: yes
  tasks: 
  - name: install apt package
    apt:
     name: apt 
     update_cache: yes

  - name: install net-tools 
    apt: 
     name: net-tools 
     state: present 

  - name: install wget
    package: 
     name: wget 
     state: present 

  - name: install vim 
    package: 
     name: vim 
     state: present 

  - name: install curl 
    package: 
     name: curl 
     state: present  

  - name: copy a file
    template:
     src: config.j2
     dest: /etc/sysctl.conf

  - name: Apply sysctl settings
    command: sudo sysctl --system
    register: sysctl_result