---
- hosts: 172.31.16.43
  become: yes
  tasks: 
  - name: update packages
    apt: 
     update_cache: yes

  - name: upgarde packages 
    apt:
     upgrade: yes 

  - name: install java 
    apt: 
     name: openjdk-17-jdk 
     state: present 

  - name: install postgresql 
    apt: 
     name: postgresql-15
     state: present 
    
  - name: create directory
    file:
     path: /opt/sonarqube
     state: directory 

  - name: copy sonarqube zip ifle 
    copy:
     src: C:\\Users\\user\\Desktop\\sonarqube\\sonarqube-25.3.0.104237.zip.zip
     dest: /opt/sonarqube/sonarqube-25.3.0.104237.zip.zip

    