--- 
- hosts: 172.31.16.43
  become: yes
  tasks: 
  - name: install apt package 
    apt:
     name: apt 
     update_cache: yes
     state: present 

  - name: install curl package 
    apt:
     name: curl 
     state: present 

  - name: install directory
    file: 
     path: /etc/apt/keyrings
     state: directory 
     mode: 0755

  - name: download docker jpg key 
    get_url:
     url: https://download.docker.com/linux/debian/gpg
     dest: /etc/apt/keyrings/docker.asc

  - name: execute linux command 
    command: sudo chmod a+r /etc/apt/keyrings/docker.asc

  - name: add repositoryyyy
    apt_repository:
     repo: deb  https://download.docker.com/linux/debian
     state: present 
     
     