--- 
- hosts: 172.31.32.138
  become: yes
  tasks: 
  - name: update apt package
    apt:
     update_cache: yes

  - name: install java
    apt:
     name: "{{myjavapack}}"
     state: present 

  - name: jenkins repository key 
    apt_key:
     url: "{{url}}"
     state: present
     
  - name: Add jenkins repository 
    apt_repository: 
     repo: "{{repo}}"
     state: present

  - name: Update apt cache
    apt:
     update_cache: yes

  - name: install jenkins
    apt: 
     name: "{{myjenkinspack}}"
     state: present 
    when: ansible_os_family=="Debian"
     
  - name: Ensure Jenkins service is started and enabled
    service:
     name: jenkins
     state: started
     enabled: yes

    


  

