---
- hosts: 172.31.16.43
  become: yes
  tasks: 
  - name: update packages
    apt: 
     update_cache: yes

  - name: upgarde packages 
    apt:
     upgrade: yes 

  - name: install java 
    apt: 
     name: openjdk-17-jdk 
     state: present 

  - name: install postgresql 
    apt: 
     name: postgresql-15
     state: present 
    
    