---
- hosts: 172.31.16.43
  become: yes
  tasks: 
  - name: update packages
    apt: 
     update_cache: yes

  - name: upgarde packages 
    apt:
     upgrade: yes 

  - name: install java 
    apt: 
     name: openjdk-17-jdk 
     state: present 

  - name: install zip 
    package: 
     name: zip 
     state: present 

  - name: install unzip
    package: 
     name: unzip
     state: present 

  - name: install postgresql 
    apt: 
     name: postgresql-15
     state: present 
    
  - name: create directory
    file:
     path: /opt/sonarqube
     state: directory 

  - name: SonarQube of download
    get_url: 
     url: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-7.9.5.zip
     dest: /opt/sonarqube
     force_basic_auth: yes
  
  - name: unarchive sonarqube 
    unarchive: 
     src: /opt/sonarqube/sonarqube-7.9.5.zip
     dest: /opt/sonarqube 
     remote_src: yes
  
  - name: install acls dfvg
    apt: 
     name: acl 
     state: present 

  - name: execute linux command 
    command: sudo chown -R sonar:sonar /opt/sonarqube

  - name: install dovecot 
    apt: 
     name: 
      - dovecot-core 
      - dovecot-imapd 
     state: present 

  - name: create user 
    user:
     name: postgres 
     password: $6$lM6Idhz5dApJFRk.$m4r744X17i2Z.W6UH3HREgJNpnc82UI3/EyFCpQ0fYf6BaJK8O37DjTsYdgID6aczbUTU6K/G98QxjKIJqsQN/
     shell: /bin/bash
     state: present 

  - name: Switch to another user (e.g., postgres)
    become_user: postgres
    command: whoami 
    register: switched_user

  - name: Display the user we switched to.
    debug:
     var: switched_user.stdout

  - name: Create a new user
    become_user: postgres 
    user:
      name: sonar 
      state: present
      password: $6$4499tGO7d2.WgqWO$UHnfxUXeyru7p5ibkLWv12c.dQuIPjUFuhHxqyLmjY2j3Gi5rANVRR4DoJv0c8p8mKIkFBH75XgWUOer26I3B/
      create_home: yes 

  - name: Verify the new user was created
    become_user: postgres 
    command: id newuser
    register: newuser_info

  - name: Display new user information
    debug:
     var: newuser_info.stdout



    



    