--- 
- hosts: 172.31.30.140
  become: yes
  tasks: 
  - name: install apt package
    apt:
     name: apt 
     update_cache: yes

  - name: install net-tools 
    apt: 
     name: net-tools 
     state: present 

  - name: install wget
    package: 
     name: wget 
     state: present 

  - name: install vim 
    package: 
     name: vim 
     state: present 

  - name: install curl 
    package: 
     name: curl 
     state: present  

  - name: copy a file
    template:
     src: config.j2
     dest: /etc/sysctl.conf

  - name: Apply sysctl settings
    command: sudo sysctl --system
    register: sysctl_result

  - name: install java 
    apt: 
     name: openjdk-17-jdk
     state: present 

  - name:  install gpg
    package: 
     name: gnupg
     state: present 

  - name: add postgre key 
    apt_key: 
     url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
     state: present 

  - name: add reposit
    command: sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" >> /etc/apt/sources.list.d/pgdg.list'

  - name: install apt package
    apt:
     name: apt 
     update_cache: yes



